/**
 * Phase 5: Reality Metrics Definitions
 * Complete specification of 60+ metrics across 14 dimensions
 * Based on DISHA 14-Dimension Diagnostic Framework v2
 */

export type MetricDataType = 'PERCENTAGE' | 'NUMBER' | 'AVERAGE' | 'RATIO' | 'DAYS' | 'TEXT';

export interface MetricDefinition {
  id: string; // 1a, 1b, 1c, etc
  dimensionId: number; // 1-14
  dimensionName: string;
  name: string; // Human readable name
  description: string; // What this metric measures
  dataType: MetricDataType;
  unit: string; // %, count, days, etc
  minValue: number;
  maxValue: number;
  formula: string; // How to calculate
  dataSources: string[]; // Where to get data
  fallback: string; // What to do if data unavailable
  example: string; // Example calculation
}

export const METRICS_DEFINITIONS: MetricDefinition[] = [
  // ============================================================================
  // DIMENSION 1: Academic Performance & Learning Outcomes (6 metrics)
  // ============================================================================

  {
    id: '1a',
    dimensionId: 1,
    dimensionName: 'Academic Performance & Learning Outcomes',
    name: 'Board Exam Pass Rate (%)',
    description: 'Percentage of students who passed board exams',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Students Passed / Students Appeared) × 100',
    dataSources: ['CBSE Portal', 'Board Result Sheets', 'School Records'],
    fallback: 'Use previous year data or request from exam cell',
    example: 'If 45 of 50 students passed: (45/50) × 100 = 90%',
  },

  {
    id: '1b',
    dimensionId: 1,
    dimensionName: 'Academic Performance & Learning Outcomes',
    name: 'Formative Assessment Average',
    description: 'Average score from internal class tests and formative assessments',
    dataType: 'AVERAGE',
    unit: 'Score (0-100)',
    minValue: 0,
    maxValue: 100,
    formula: 'Sum of all formative scores / Number of students assessed',
    dataSources: ['LMS/Gradebook', 'Teacher Mark Registers', 'Assessment Records'],
    fallback: 'Audit mark registers; introduce digital template next term',
    example: 'Class average formative score: 75/100',
  },

  {
    id: '1c',
    dimensionId: 1,
    dimensionName: 'Academic Performance & Learning Outcomes',
    name: 'Students Below Grade-Level Benchmark (%)',
    description: 'Percentage of students below grade-level expectations',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Students Below Cutoff / Total Tested) × 100',
    dataSources: ['Diagnostic Tests', 'NCERT Assessments', 'Internal Benchmarks'],
    fallback: 'Use % below 50% on internal formative assessments',
    example: 'If 15 of 100 students below benchmark: (15/100) × 100 = 15%',
  },

  {
    id: '1d',
    dimensionId: 1,
    dimensionName: 'Academic Performance & Learning Outcomes',
    name: 'Year-on-Year Student Growth',
    description: 'Average improvement in student scores from previous year',
    dataType: 'AVERAGE',
    unit: 'Points',
    minValue: -50,
    maxValue: 50,
    formula: 'Average of (Current Score - Previous Score) for all linked students',
    dataSources: ['Student ID Matching', 'Historical Score Records'],
    fallback: 'Use cohort pass-rate change until student linking ready',
    example: 'Average growth across class: +5 points YoY',
  },

  {
    id: '1e',
    dimensionId: 1,
    dimensionName: 'Academic Performance & Learning Outcomes',
    name: 'Topic-Wise Item Analysis (% Incorrect)',
    description: 'Identification of most-failed topics/concepts',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Incorrect Responses / Total Responses) × 100, ranked by topic',
    dataSources: ['Exam Answer Analysis', 'OMR Results', 'Question-wise Marks'],
    fallback: 'Ask subject teachers to tag marks by topic during next correction',
    example: 'Topic "Fractions": 45% students incorrect',
  },

  {
    id: '1f',
    dimensionId: 1,
    dimensionName: 'Academic Performance & Learning Outcomes',
    name: 'Homework Completion Rate (%)',
    description: 'Percentage of assigned homework completed and submitted',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Submissions Received / Assignments Given) × 100',
    dataSources: ['LMS Submission Logs', 'Homework Registers', 'Teacher Records'],
    fallback: 'Start simple homework register per class next term',
    example: 'If 80 of 100 assignments submitted: (80/100) × 100 = 80%',
  },

  // ============================================================================
  // DIMENSION 2: Curriculum & Pedagogy Quality (5 metrics)
  // ============================================================================

  {
    id: '2a',
    dimensionId: 2,
    dimensionName: 'Curriculum & Pedagogy Quality',
    name: 'Effective Teaching Lessons (%)',
    description: 'Percentage of observed lessons rated as effective',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Lessons Rated Effective / Total Lessons Observed) × 100',
    dataSources: ['Classroom Observations', 'Inspection Reports', 'Admin Notes'],
    fallback: 'Use teacher self-assessment rubric',
    example: 'Observed 20 lessons; 15 effective: (15/20) × 100 = 75%',
  },

  {
    id: '2b',
    dimensionId: 2,
    dimensionName: 'Curriculum & Pedagogy Quality',
    name: 'CPD Hours Per Teacher (Annual)',
    description: 'Average professional development hours per teacher per year',
    dataType: 'NUMBER',
    unit: 'Hours',
    minValue: 0,
    maxValue: 500,
    formula: 'Total CPD Hours / Number of Teachers',
    dataSources: ['CPD Records', 'Workshop Attendance', 'Training Logs'],
    fallback: 'Survey teachers on hours spent in development',
    example: 'Total 2000 hours / 100 teachers = 20 hours per teacher',
  },

  {
    id: '2c',
    dimensionId: 2,
    dimensionName: 'Curriculum & Pedagogy Quality',
    name: 'Activity-Based to Lecture-Based Ratio',
    description: 'Ratio of activity-based lessons to lecture-based lessons',
    dataType: 'RATIO',
    unit: 'Ratio',
    minValue: 0,
    maxValue: 10,
    formula: 'Number of Activity-Based Lessons / Number of Lecture-Based Lessons',
    dataSources: ['Lesson Plans', 'Classroom Observations'],
    fallback: 'Teacher survey on teaching methods used',
    example: '15 activity lessons / 5 lecture lessons = 3:1 ratio',
  },

  {
    id: '2d',
    dimensionId: 2,
    dimensionName: 'Curriculum & Pedagogy Quality',
    name: 'Curriculum Coverage by Checkpoint (%)',
    description: 'Percentage of planned topics covered by each checkpoint',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: 'Average of (Topics Covered / Topics Planned) for all checkpoints × 100',
    dataSources: ['Lesson Plans', 'Pacing Guides', 'Teacher Reports'],
    fallback: 'Review lesson plans at end of term',
    example: 'Q1 coverage: 95%, Q2 coverage: 92% → Average 93.5%',
  },

  {
    id: '2e',
    dimensionId: 2,
    dimensionName: 'Curriculum & Pedagogy Quality',
    name: 'Projects & Applied Learning (Count)',
    description: 'Number of projects or applied learning activities documented',
    dataType: 'NUMBER',
    unit: 'Projects',
    minValue: 0,
    maxValue: 1000,
    formula: 'Total documented projects across all classes',
    dataSources: ['Project Records', 'Student Portfolios', 'Teacher Documentation'],
    fallback: 'Survey teachers on projects undertaken this term',
    example: 'School has 35 documented projects this year',
  },

  // ============================================================================
  // DIMENSION 3: Teacher Quality, Development & Retention (6 metrics)
  // ============================================================================

  {
    id: '3a',
    dimensionId: 3,
    dimensionName: 'Teacher Quality, Development & Retention',
    name: 'Teacher Turnover Rate (%)',
    description: 'Percentage of teachers who left during the year',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Teachers Left / Average Teachers Employed) × 100',
    dataSources: ['HR Records', 'Resignation Letters', 'Payroll Data'],
    fallback: 'Count resignations from start of year',
    example: 'If 100 avg teachers, 5 left: (5/100) × 100 = 5%',
  },

  {
    id: '3b',
    dimensionId: 3,
    dimensionName: 'Teacher Quality, Development & Retention',
    name: 'Average Teacher Tenure (Years)',
    description: 'Average years of experience at this school',
    dataType: 'AVERAGE',
    unit: 'Years',
    minValue: 0,
    maxValue: 50,
    formula: 'Sum of all teacher tenures / Number of teachers',
    dataSources: ['HR Records', 'Joining Dates'],
    fallback: 'Survey teachers on years at school',
    example: 'Average tenure: 6.5 years',
  },

  {
    id: '3c',
    dimensionId: 3,
    dimensionName: 'Teacher Quality, Development & Retention',
    name: 'Qualified Teachers (%)',
    description: 'Percentage of teachers with required qualifications',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Qualified Teachers / Total Teachers) × 100',
    dataSources: ['Qualification Certificates', 'HR Files', 'Credential Verification'],
    fallback: 'Use previous year data',
    example: 'If 98 of 100 qualified: (98/100) × 100 = 98%',
  },

  {
    id: '3d',
    dimensionId: 3,
    dimensionName: 'Teacher Quality, Development & Retention',
    name: 'Teacher Absence Rate (%)',
    description: 'Percentage of days teachers were absent',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Total Days Absent / Total Possible Days) × 100',
    dataSources: ['Attendance Records', 'Biometric Data'],
    fallback: 'Manual attendance register review',
    example: 'If 500 days absent / 25000 possible: (500/25000) × 100 = 2%',
  },

  {
    id: '3e',
    dimensionId: 3,
    dimensionName: 'Teacher Quality, Development & Retention',
    name: 'Student-Teacher Ratio',
    description: 'Number of students per teaching staff member',
    dataType: 'RATIO',
    unit: 'Students:Teachers',
    minValue: 0,
    maxValue: 100,
    formula: 'Total Enrolled Students / Total Teaching Staff (FTE)',
    dataSources: ['Enrollment Records', 'Payroll', 'Staffing Plan'],
    fallback: 'Use current year enrollment data',
    example: '2500 students / 100 teachers = 25:1 ratio',
  },

  {
    id: '3f',
    dimensionId: 3,
    dimensionName: 'Teacher Quality, Development & Retention',
    name: 'Substitute Coverage (%)',
    description: 'Percentage of periods with substitute teachers',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Periods with Substitute / Total Periods Taught) × 100',
    dataSources: ['Class Registers', 'Substitute Logs'],
    fallback: 'Manual review of absence coverage',
    example: 'If 50 of 5000 periods had substitute: (50/5000) × 100 = 1%',
  },

  // ============================================================================
  // DIMENSION 4: Student Wellbeing & Mental Health (5 metrics)
  // ============================================================================

  {
    id: '4a',
    dimensionId: 4,
    dimensionName: 'Student Wellbeing & Mental Health',
    name: 'Counselor Sessions Per Month',
    description: 'Average counseling sessions per month and caseload per counselor',
    dataType: 'NUMBER',
    unit: 'Sessions',
    minValue: 0,
    maxValue: 1000,
    formula: 'Total Sessions / Months Tracked; Distinct Students / Total Counselors',
    dataSources: ['Counselor Records', 'Session Logs'],
    fallback: 'Survey counselors on sessions conducted',
    example: '400 sessions / 12 months = 33 sessions/month; 250 students / 2 counselors = 125 caseload',
  },

  {
    id: '4b',
    dimensionId: 4,
    dimensionName: 'Student Wellbeing & Mental Health',
    name: 'Bullying Incident Resolution Time (Days)',
    description: 'Average days to resolve reported bullying incidents',
    dataType: 'DAYS',
    unit: 'Days',
    minValue: 0,
    maxValue: 365,
    formula: 'Average of (Resolved Date - Reported Date) for all resolved incidents',
    dataSources: ['Incident Reports', 'Resolution Records'],
    fallback: 'Survey admin on resolution timeline',
    example: 'Average 5 days to resolve bullying incidents',
  },

  {
    id: '4c',
    dimensionId: 4,
    dimensionName: 'Student Wellbeing & Mental Health',
    name: 'Absences Flagged for Stress (%)',
    description: 'Percentage of absences marked as stress/anxiety related',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Absences with Stress Flag / Total Absences) × 100',
    dataSources: ['Absence Records', 'Staff Notes'],
    fallback: 'Manual review of absences in past month',
    example: 'If 50 of 1000 absences flagged: (50/1000) × 100 = 5%',
  },

  {
    id: '4d',
    dimensionId: 4,
    dimensionName: 'Student Wellbeing & Mental Health',
    name: 'SEL Program Participation (%)',
    description: 'Percentage of students attending social-emotional learning programs',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Students Attending SEL / Total Enrolled) × 100',
    dataSources: ['Program Records', 'Attendance Logs'],
    fallback: 'Survey teachers on SEL participation',
    example: 'If 1800 of 2500 students attend: (1800/2500) × 100 = 72%',
  },

  {
    id: '4e',
    dimensionId: 4,
    dimensionName: 'Student Wellbeing & Mental Health',
    name: 'Wellbeing Survey Response Rate (%)',
    description: 'Percentage of students completing wellbeing surveys',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Surveys Completed / Surveys Sent) × 100',
    dataSources: ['Survey Responses', 'Distribution Lists'],
    fallback: 'Manual survey distribution to classes',
    example: 'If 2000 of 2500 responded: (2000/2500) × 100 = 80%',
  },

  // ============================================================================
  // DIMENSIONS 5-14 (abbreviated for brevity, but same structure applies)
  // ============================================================================

  // Dimension 5: Student Discipline & Behavior (5 metrics)
  {
    id: '5a',
    dimensionId: 5,
    dimensionName: 'Student Discipline & Behavior',
    name: 'Consistent Discipline Application (%)',
    description: 'Percentage of discipline cases handled consistently',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Consistent Cases / Total Cases Reviewed) × 100',
    dataSources: ['Discipline Records', 'Admin Review'],
    fallback: 'Sample review of discipline records',
    example: '85% of cases applied policy consistently',
  },

  {
    id: '5b',
    dimensionId: 5,
    dimensionName: 'Student Discipline & Behavior',
    name: 'Students Understanding Rules (%)',
    description: 'Percentage of students who understand school rules',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: 'Survey results on rule understanding',
    dataSources: ['Student Survey', 'Assessment'],
    fallback: 'Teacher observation scores',
    example: '78% students understand rules well',
  },

  {
    id: '5c',
    dimensionId: 5,
    dimensionName: 'Student Discipline & Behavior',
    name: 'Restorative vs Punitive Discipline Ratio',
    description: 'Ratio of restorative to purely punitive actions',
    dataType: 'RATIO',
    unit: 'Ratio',
    minValue: 0,
    maxValue: 10,
    formula: 'Restorative Actions / Purely Punitive Actions',
    dataSources: ['Discipline Records'],
    fallback: 'Manual case-by-case review',
    example: '60 restorative / 20 punitive = 3:1 ratio',
  },

  {
    id: '5d',
    dimensionId: 5,
    dimensionName: 'Student Discipline & Behavior',
    name: 'Parent Involvement in Discipline (%)',
    description: 'Percentage of serious incidents with parent involvement',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Serious Cases with Parent Contact / Total Serious Cases) × 100',
    dataSources: ['Incident Records', 'Contact Logs'],
    fallback: 'Sample review of serious incidents',
    example: '95% of serious cases involved parents',
  },

  {
    id: '5e',
    dimensionId: 5,
    dimensionName: 'Student Discipline & Behavior',
    name: 'Rule Compliance Rate (%)',
    description: 'Percentage of students consistently following rules',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: 'Teacher rating of rule compliance',
    dataSources: ['Teacher Observation', 'Incident Counts'],
    fallback: 'Count students with zero incidents vs total',
    example: '82% of students have good compliance',
  },

  // Dimension 6: Infrastructure & Facilities (4 metrics)
  {
    id: '6a',
    dimensionId: 6,
    dimensionName: 'Infrastructure & Facilities',
    name: 'Facilities Maintenance Score (0-100)',
    description: 'Quality rating of buildings and facilities',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Inspection score on cleanliness, safety, repair',
    dataSources: ['Inspection Reports', 'Maintenance Logs'],
    fallback: 'Staff and student ratings',
    example: 'Overall maintenance score: 82/100',
  },

  {
    id: '6b',
    dimensionId: 6,
    dimensionName: 'Infrastructure & Facilities',
    name: 'Classroom Resource Adequacy (%)',
    description: 'Percentage of classrooms with adequate resources',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Classrooms with Adequate Resources / Total Classrooms) × 100',
    dataSources: ['Resource Inventory', 'Teacher Reports'],
    fallback: 'Survey teachers on classroom readiness',
    example: '88% of classrooms well-equipped',
  },

  {
    id: '6c',
    dimensionId: 6,
    dimensionName: 'Infrastructure & Facilities',
    name: 'Specialized Spaces Available (Count)',
    description: 'Number of specialized learning spaces',
    dataType: 'NUMBER',
    unit: 'Spaces',
    minValue: 0,
    maxValue: 100,
    formula: 'Count of sports fields, art rooms, music rooms, labs, etc.',
    dataSources: ['Facility Map', 'Inventory'],
    fallback: 'Physical count of specialized areas',
    example: 'School has 12 specialized learning spaces',
  },

  {
    id: '6d',
    dimensionId: 6,
    dimensionName: 'Infrastructure & Facilities',
    name: 'Sanitation Facilities Score (0-100)',
    description: 'Quality rating of toilets, water, and hygiene facilities',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Inspection score on cleanliness, functionality, availability',
    dataSources: ['Inspection Reports', 'Maintenance Logs'],
    fallback: 'Staff and student ratings',
    example: 'Sanitation facilities score: 75/100',
  },

  // Dimension 7: Safety & Security (5 metrics)
  {
    id: '7a',
    dimensionId: 7,
    dimensionName: 'Safety & Security',
    name: 'Student Injury Incidents (Count/Year)',
    description: 'Number of reported student injuries on campus',
    dataType: 'NUMBER',
    unit: 'Incidents',
    minValue: 0,
    maxValue: 1000,
    formula: 'Total documented injury incidents in past 12 months',
    dataSources: ['Incident Reports', 'First Aid Records'],
    fallback: 'Survey staff on incidents this year',
    example: 'School had 12 reported injuries this year',
  },

  {
    id: '7b',
    dimensionId: 7,
    dimensionName: 'Safety & Security',
    name: 'Child Protection Incidents (%)',
    description: 'Percentage handled appropriately when reported',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Incidents Handled Properly / Total Reported) × 100',
    dataSources: ['Incident Reports', 'Investigation Records'],
    fallback: 'Review past incidents for appropriateness',
    example: '100% of child protection incidents handled appropriately',
  },

  {
    id: '7c',
    dimensionId: 7,
    dimensionName: 'Safety & Security',
    name: 'Campus Access Control Score (0-100)',
    description: 'Quality rating of access control systems',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Inspection score on gate security, entry/exit procedures',
    dataSources: ['Security Audit', 'Admin Report'],
    fallback: 'Staff assessment of security measures',
    example: 'Access control score: 88/100',
  },

  {
    id: '7d',
    dimensionId: 7,
    dimensionName: 'Safety & Security',
    name: 'Emergency Drills Conducted (Count/Year)',
    description: 'Number of safety drills conducted annually',
    dataType: 'NUMBER',
    unit: 'Drills',
    minValue: 0,
    maxValue: 52,
    formula: 'Total emergency drills (fire, earthquake, lockdown) per year',
    dataSources: ['Drill Records', 'Admin Logs'],
    fallback: 'Survey staff on drills conducted',
    example: 'School conducted 8 emergency drills this year',
  },

  {
    id: '7e',
    dimensionId: 7,
    dimensionName: 'Safety & Security',
    name: 'Parent Communication on Incidents (%)',
    description: 'Percentage of safety incidents communicated to parents',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Incidents Communicated to Parents / Total Incidents) × 100',
    dataSources: ['Communication Records', 'Incident Logs'],
    fallback: 'Review incident files for parent notices',
    example: '95% of incidents communicated to affected families',
  },

  // Dimension 8: Parent Satisfaction & Engagement (5 metrics)
  {
    id: '8a',
    dimensionId: 8,
    dimensionName: 'Parent Satisfaction & Engagement',
    name: 'Teacher-Parent Communication Frequency',
    description: 'How often parents receive updates from teachers',
    dataType: 'TEXT',
    unit: 'Frequency',
    minValue: 0,
    maxValue: 1,
    formula: 'Average communication frequency from teacher surveys',
    dataSources: ['Parent Survey', 'Communication Records'],
    fallback: 'Survey parents directly',
    example: 'Monthly updates on student progress',
  },

  {
    id: '8b',
    dimensionId: 8,
    dimensionName: 'Parent Satisfaction & Engagement',
    name: 'Parent Involvement Opportunities (Count)',
    description: 'Number of ways parents can engage with school',
    dataType: 'NUMBER',
    unit: 'Opportunities',
    minValue: 0,
    maxValue: 100,
    formula: 'Count of volunteer opportunities, committees, events',
    dataSources: ['School Calendar', 'Parent Portal'],
    fallback: 'Manual count of engagement activities',
    example: 'School offers 15 ways for parents to get involved',
  },

  {
    id: '8c',
    dimensionId: 8,
    dimensionName: 'Parent Satisfaction & Engagement',
    name: 'Parent Event Attendance Rate (%)',
    description: 'Percentage of parents attending school events',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Parents Attending / Total Families) × 100 (avg across events)',
    dataSources: ['Event Attendance', 'Registration Records'],
    fallback: 'Count attendees vs families at next event',
    example: '65% of families attend at least one event per year',
  },

  {
    id: '8d',
    dimensionId: 8,
    dimensionName: 'Parent Satisfaction & Engagement',
    name: 'Parent Concerns Response Time (Days)',
    description: 'Average days to respond to parent concerns',
    dataType: 'DAYS',
    unit: 'Days',
    minValue: 0,
    maxValue: 365,
    formula: 'Average of (Response Date - Concern Date) for all concerns',
    dataSources: ['Complaint/Concern Tracking'],
    fallback: 'Survey parents on response speed',
    example: 'Average response time: 2 business days',
  },

  {
    id: '8e',
    dimensionId: 8,
    dimensionName: 'Parent Satisfaction & Engagement',
    name: 'Overall Parent Satisfaction Score (0-100)',
    description: 'Parent satisfaction with school',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Average from parent satisfaction survey',
    dataSources: ['Parent Survey'],
    fallback: 'Conduct parent survey',
    example: 'Parent satisfaction score: 78/100',
  },

  // Dimension 9: Student Satisfaction & Engagement (5 metrics)
  {
    id: '9a',
    dimensionId: 9,
    dimensionName: 'Student Satisfaction & Engagement',
    name: 'School Enjoyment Score (0-100)',
    description: 'How much students enjoy being at school',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Average from student satisfaction survey',
    dataSources: ['Student Survey'],
    fallback: 'Conduct student survey',
    example: 'Student enjoyment score: 72/100',
  },

  {
    id: '9b',
    dimensionId: 9,
    dimensionName: 'Student Satisfaction & Engagement',
    name: 'Co-Curricular Participation Rate (%)',
    description: 'Percentage of students participating in clubs/sports',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Students in Activities / Total Students) × 100',
    dataSources: ['Activity Enrollment', 'Club Records'],
    fallback: 'Survey student participation',
    example: '68% of students participate in at least one activity',
  },

  {
    id: '9c',
    dimensionId: 9,
    dimensionName: 'Student Satisfaction & Engagement',
    name: 'Student Voice Opportunities (Count)',
    description: 'Number of ways students can express opinions',
    dataType: 'NUMBER',
    unit: 'Opportunities',
    minValue: 0,
    maxValue: 50,
    formula: 'Count of student government, surveys, feedback channels',
    dataSources: ['Student Portal', 'Club Records'],
    fallback: 'Manual count of student voice activities',
    example: 'School has 8 channels for student input',
  },

  {
    id: '9d',
    dimensionId: 9,
    dimensionName: 'Student Satisfaction & Engagement',
    name: 'Peer Relationships Quality Score (0-100)',
    description: 'Quality of friendships and social connections',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Average from social connection survey',
    dataSources: ['Student Survey', 'Social Assessment'],
    fallback: 'Teacher observation of peer dynamics',
    example: 'Peer relationships quality score: 75/100',
  },

  {
    id: '9e',
    dimensionId: 9,
    dimensionName: 'Student Satisfaction & Engagement',
    name: 'Overall Student Satisfaction Score (0-100)',
    description: 'Overall student satisfaction with school',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Average from comprehensive student survey',
    dataSources: ['Student Survey'],
    fallback: 'Conduct student survey',
    example: 'Student satisfaction score: 70/100',
  },

  // Dimension 10: Leadership & Governance (5 metrics)
  {
    id: '10a',
    dimensionId: 10,
    dimensionName: 'Leadership & Governance',
    name: 'Vision Clarity Score (0-100)',
    description: 'How clearly school vision is communicated',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Staff and parent understanding of school vision',
    dataSources: ['Staff Survey', 'Parent Survey'],
    fallback: 'Leadership self-assessment',
    example: 'Vision clarity score: 82/100',
  },

  {
    id: '10b',
    dimensionId: 10,
    dimensionName: 'Leadership & Governance',
    name: 'Stakeholder Input in Decisions (%)',
    description: 'Percentage of major decisions with stakeholder input',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Decisions with Input / Total Decisions) × 100',
    dataSources: ['Decision Logs', 'Meeting Minutes'],
    fallback: 'Review major decisions from past year',
    example: '70% of major decisions included stakeholder input',
  },

  {
    id: '10c',
    dimensionId: 10,
    dimensionName: 'Leadership & Governance',
    name: 'Board Governance Quality Score (0-100)',
    description: 'Quality of board oversight and governance',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Assessment against governance best practices',
    dataSources: ['Governance Audit', 'Board Self-Assessment'],
    fallback: 'Governance rubric evaluation',
    example: 'Board governance score: 78/100',
  },

  {
    id: '10d',
    dimensionId: 10,
    dimensionName: 'Leadership & Governance',
    name: 'Leadership Accessibility Score (0-100)',
    description: 'How accessible and responsive leadership is to staff',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Staff rating of leadership accessibility',
    dataSources: ['Staff Survey'],
    fallback: 'Staff feedback meetings',
    example: 'Leadership accessibility score: 74/100',
  },

  {
    id: '10e',
    dimensionId: 10,
    dimensionName: 'Leadership & Governance',
    name: 'Professional Development Opportunities (Count)',
    description: 'Number of PD opportunities offered to staff',
    dataType: 'NUMBER',
    unit: 'Opportunities',
    minValue: 0,
    maxValue: 100,
    formula: 'Count of workshops, courses, and training sessions offered',
    dataSources: ['PD Calendar', 'Training Records'],
    fallback: 'Survey staff on PD availability',
    example: 'School offers 12 PD opportunities this year',
  },

  // Dimension 11: Financial Health & Sustainability (4 metrics)
  {
    id: '11a',
    dimensionId: 11,
    dimensionName: 'Financial Health & Sustainability',
    name: 'Fee Transparency Score (0-100)',
    description: 'Clarity and transparency of school fees',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Parent understanding of fee structure',
    dataSources: ['Parent Survey', 'Fee Documentation'],
    fallback: 'Audit fee communication materials',
    example: 'Fee transparency score: 81/100',
  },

  {
    id: '11b',
    dimensionId: 11,
    dimensionName: 'Financial Health & Sustainability',
    name: 'Teacher Salary Timeliness (%)',
    description: 'Percentage of teachers paid on time',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Timely Payments / Total Payments) × 100',
    dataSources: ['Payroll Records'],
    fallback: 'Survey teachers on payment timeliness',
    example: '100% of teacher salaries paid on time',
  },

  {
    id: '11c',
    dimensionId: 11,
    dimensionName: 'Financial Health & Sustainability',
    name: 'Infrastructure Investment (% of Revenue)',
    description: 'Percentage of revenue invested in improvements',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Infrastructure Spending / Total Revenue) × 100',
    dataSources: ['Budget Records', 'Expense Reports'],
    fallback: 'Review annual budget allocation',
    example: '12% of revenue invested in infrastructure',
  },

  {
    id: '11d',
    dimensionId: 11,
    dimensionName: 'Financial Health & Sustainability',
    name: 'Resource Efficiency Score (0-100)',
    description: 'How efficiently resources are used',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Assessment of resource allocation and waste reduction',
    dataSources: ['Audit Reports', 'Admin Assessment'],
    fallback: 'Finance team self-assessment',
    example: 'Resource efficiency score: 76/100',
  },

  // Dimension 12: Admissions, Enrollment & Market Position (5 metrics)
  {
    id: '12a',
    dimensionId: 12,
    dimensionName: 'Admissions, Enrollment & Market Position',
    name: 'Applicant Quality Score (0-100)',
    description: 'Academic quality of admitted students',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Average entrance exam scores or prior academics',
    dataSources: ['Entrance Exams', 'Prior School Records'],
    fallback: 'Transcript review of enrolled students',
    example: 'Applicant quality score: 80/100',
  },

  {
    id: '12b',
    dimensionId: 12,
    dimensionName: 'Admissions, Enrollment & Market Position',
    name: 'Admissions Fairness Score (0-100)',
    description: 'Fairness and transparency of admissions',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Assessment of admissions criteria and process',
    dataSources: ['Parent Survey', 'Process Audit'],
    fallback: 'Admissions committee review',
    example: 'Admissions fairness score: 85/100',
  },

  {
    id: '12c',
    dimensionId: 12,
    dimensionName: 'Admissions, Enrollment & Market Position',
    name: 'Brand Reputation Score (0-100)',
    description: 'School reputation for academic excellence',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Community perception of school reputation',
    dataSources: ['Community Survey', 'Media Mentions'],
    fallback: 'Local education rankings review',
    example: 'Brand reputation score: 79/100',
  },

  {
    id: '12d',
    dimensionId: 12,
    dimensionName: 'Admissions, Enrollment & Market Position',
    name: 'Student Retention Rate (%)',
    description: 'Percentage of students continuing through upper grades',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Students Retained / Eligible Students) × 100',
    dataSources: ['Enrollment Records'],
    fallback: 'Track cohort progress',
    example: '88% of students continue to next grade',
  },

  {
    id: '12e',
    dimensionId: 12,
    dimensionName: 'Admissions, Enrollment & Market Position',
    name: 'Alumni Network Engagement (%)',
    description: 'Percentage of alumni engaged with school',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Alumni Engaged / Total Alumni Tracked) × 100',
    dataSources: ['Alumni Database', 'Engagement Records'],
    fallback: 'Build alumni database this year',
    example: '25% of alumni actively engaged',
  },

  // Dimension 13: Technology & Digital Readiness (5 metrics)
  {
    id: '13a',
    dimensionId: 13,
    dimensionName: 'Technology & Digital Readiness',
    name: 'Student Device Access Rate (%)',
    description: 'Percentage of students with access to technology',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Students with Access / Total Students) × 100',
    dataSources: ['Device Inventory', 'Lab Usage Logs'],
    fallback: 'Survey students on device access',
    example: '95% of students have laptop/tablet access',
  },

  {
    id: '13b',
    dimensionId: 13,
    dimensionName: 'Technology & Digital Readiness',
    name: 'Teacher Technology Proficiency Score (0-100)',
    description: 'Teacher ability to use technology in teaching',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Assessment of technology integration skills',
    dataSources: ['Professional Assessment', 'Classroom Observation'],
    fallback: 'Self-assessment from teachers',
    example: 'Teacher tech proficiency score: 72/100',
  },

  {
    id: '13c',
    dimensionId: 13,
    dimensionName: 'Technology & Digital Readiness',
    name: 'Digital Learning System Adoption Rate (%)',
    description: 'Percentage using digital learning management system',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Active Users / Total Users) × 100',
    dataSources: ['LMS Login Logs', 'Usage Analytics'],
    fallback: 'Survey teachers on LMS usage',
    example: '78% of teachers actively use LMS',
  },

  {
    id: '13d',
    dimensionId: 13,
    dimensionName: 'Technology & Digital Readiness',
    name: 'Digital Literacy Competency (%)',
    description: 'Percentage of students with digital skills',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Digitally Literate Students / Total Students) × 100',
    dataSources: ['Skills Assessment', 'Course Completion'],
    fallback: 'Teacher assessment of digital skills',
    example: '82% of students have basic digital literacy',
  },

  {
    id: '13e',
    dimensionId: 13,
    dimensionName: 'Technology & Digital Readiness',
    name: 'Infrastructure Reliability Uptime (%)',
    description: 'Percentage of time systems are operational',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Uptime Hours / Total Hours) × 100',
    dataSources: ['System Logs', 'IT Records'],
    fallback: 'IT team report on downtime incidents',
    example: '99.2% system uptime this year',
  },

  // Dimension 14: Co-curricular, Extracurricular & Holistic Development (4 metrics)
  {
    id: '14a',
    dimensionId: 14,
    dimensionName: 'Co-curricular, Extracurricular & Holistic Development',
    name: 'Activity Diversity Score (0-100)',
    description: 'Variety of activities available (sports, arts, clubs)',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Assessment of range of activities offered',
    dataSources: ['Activity Calendar', 'Club Records'],
    fallback: 'Manual count of activity types',
    example: 'Activity diversity score: 84/100',
  },

  {
    id: '14b',
    dimensionId: 14,
    dimensionName: 'Co-curricular, Extracurricular & Holistic Development',
    name: 'Life Skills Development Score (0-100)',
    description: 'Development of leadership, teamwork, creativity',
    dataType: 'NUMBER',
    unit: 'Score',
    minValue: 0,
    maxValue: 100,
    formula: 'Assessment of life skills outcomes',
    dataSources: ['Portfolio Review', 'Teacher Assessment'],
    fallback: 'Student self-assessment of skills',
    example: 'Life skills development score: 76/100',
  },

  {
    id: '14c',
    dimensionId: 14,
    dimensionName: 'Co-curricular, Extracurricular & Holistic Development',
    name: 'Achievement Recognition Events (Count/Year)',
    description: 'Number of events celebrating student achievements',
    dataType: 'NUMBER',
    unit: 'Events',
    minValue: 0,
    maxValue: 52,
    formula: 'Count of recognition events (award ceremonies, showcases)',
    dataSources: ['Event Calendar', 'Admin Records'],
    fallback: 'Survey staff on recognition events',
    example: 'School holds 6 major recognition events per year',
  },

  {
    id: '14d',
    dimensionId: 14,
    dimensionName: 'Co-curricular, Extracurricular & Holistic Development',
    name: 'Community Service Participation Rate (%)',
    description: 'Percentage of students engaged in service',
    dataType: 'PERCENTAGE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    formula: '(Students in Service / Total Students) × 100',
    dataSources: ['Service Records', 'Participation Logs'],
    fallback: 'Survey students on service participation',
    example: '71% of students participate in community service',
  },
];

/**
 * Helper functions
 */

export const getMetricById = (id: string): MetricDefinition | undefined => {
  return METRICS_DEFINITIONS.find((m) => m.id === id);
};

export const getMetricsByDimension = (dimensionId: number): MetricDefinition[] => {
  return METRICS_DEFINITIONS.filter((m) => m.dimensionId === dimensionId);
};

export const getTotalMetricCount = (): number => {
  return METRICS_DEFINITIONS.length;
};

export const getMetricsByType = (dataType: MetricDataType): MetricDefinition[] => {
  return METRICS_DEFINITIONS.filter((m) => m.dataType === dataType);
};

export const getMetricsGroupedByDimension = (): Record<number, MetricDefinition[]> => {
  const grouped: Record<number, MetricDefinition[]> = {};

  METRICS_DEFINITIONS.forEach((metric) => {
    if (!grouped[metric.dimensionId]) {
      grouped[metric.dimensionId] = [];
    }
    grouped[metric.dimensionId].push(metric);
  });

  return grouped;
};
