"use strict";
/**
 * First Opinion Engine v3 - onCycleCompletion Firestore Trigger
 * Auto-generates early warnings when cycle scores are calculated
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.onCycleCompletion = void 0;
const functions = __importStar(require("firebase-functions"));
const admin = __importStar(require("firebase-admin"));
exports.onCycleCompletion = functions.firestore
    .document('schools/{schoolId}/assessmentCycles/{cycleId}')
    .onWrite(async (change, context) => {
    try {
        const { schoolId, cycleId } = context.params;
        const after = change.after.data();
        if (!after || !after.scores) {
            return { status: 'skipped: no scores' };
        }
        const scores = after.scores;
        const healthIndex = scores.healthIndex || 0;
        const gap = scores.gap || 0;
        let level;
        let score;
        let interpretation;
        if (healthIndex < 40) {
            level = 'CRITICAL';
            score = 90;
            interpretation = `Critical: Health index ${healthIndex.toFixed(1)} requires immediate intervention`;
        }
        else if (healthIndex < 50) {
            level = 'RED';
            score = 70;
            interpretation = `Red: Health index ${healthIndex.toFixed(1)} indicates serious challenges`;
        }
        else if (healthIndex < 65) {
            level = 'YELLOW';
            score = 50;
            interpretation = `Yellow: Health index ${healthIndex.toFixed(1)} requires monitoring`;
        }
        else {
            level = 'GREEN';
            score = 20;
            interpretation = `Green: Health index ${healthIndex.toFixed(1)} shows strong performance`;
        }
        if (gap > 25)
            score += 15;
        score = Math.min(100, score);
        const cycleRef = admin
            .firestore()
            .collection('schools')
            .doc(schoolId)
            .collection('assessmentCycles')
            .doc(cycleId);
        await cycleRef.collection('warnings').doc('latest').set({
            level,
            score,
            interpretation,
            healthIndex,
            gap,
            s_sub: scores.s_sub,
            m_obj: scores.m_obj,
            quadrant: scores.quadrant,
            respondentCount: after.respondentCount || 0,
            createdAt: admin.firestore.Timestamp.now(),
            autoGenerated: true,
        }, { merge: true });
        return { status: 'success', level, score };
    }
    catch (error) {
        console.error('onCycleCompletion error:', error);
        return { status: 'error', error: error.message };
    }
});
exports.default = exports.onCycleCompletion;
//# sourceMappingURL=onCycleCompletion.js.map