/**
 * First Opinion Engine v3 - onCycleCompletion Firestore Trigger
 * Auto-generates early warnings when cycle scores are calculated
 */

import * as functions from 'firebase-functions'
import * as admin from 'firebase-admin'

interface CycleData {
  scores?: {
    healthIndex: number
    gap: number
    s_sub: number
    m_obj: number
    quadrant: string
  }
  respondentCount?: number
  status?: string
}

export const onCycleCompletion = functions.firestore
  .document('schools/{schoolId}/assessmentCycles/{cycleId}')
  .onWrite(async (change, context) => {
    try {
      const { schoolId, cycleId } = context.params
      const after = change.after.data() as CycleData | undefined

      if (!after || !after.scores) {
        return { status: 'skipped: no scores' }
      }

      const scores = after.scores
      const healthIndex = scores.healthIndex || 0
      const gap = scores.gap || 0

      let level: string
      let score: number
      let interpretation: string

      if (healthIndex < 40) {
        level = 'CRITICAL'
        score = 90
        interpretation = `Critical: Health index ${healthIndex.toFixed(1)} requires immediate intervention`
      } else if (healthIndex < 50) {
        level = 'RED'
        score = 70
        interpretation = `Red: Health index ${healthIndex.toFixed(1)} indicates serious challenges`
      } else if (healthIndex < 65) {
        level = 'YELLOW'
        score = 50
        interpretation = `Yellow: Health index ${healthIndex.toFixed(1)} requires monitoring`
      } else {
        level = 'GREEN'
        score = 20
        interpretation = `Green: Health index ${healthIndex.toFixed(1)} shows strong performance`
      }

      if (gap > 25) score += 15
      score = Math.min(100, score)

      const cycleRef = admin
        .firestore()
        .collection('schools')
        .doc(schoolId)
        .collection('assessmentCycles')
        .doc(cycleId)

      await cycleRef.collection('warnings').doc('latest').set(
        {
          level,
          score,
          interpretation,
          healthIndex,
          gap,
          s_sub: scores.s_sub,
          m_obj: scores.m_obj,
          quadrant: scores.quadrant,
          respondentCount: after.respondentCount || 0,
          createdAt: admin.firestore.Timestamp.now(),
          autoGenerated: true,
        },
        { merge: true }
      )

      return { status: 'success', level, score }
    } catch (error: any) {
      console.error('onCycleCompletion error:', error)
      return { status: 'error', error: error.message }
    }
  })

export default onCycleCompletion
