import * as functions from "firebase-functions";
export declare const initializeDISHADatabase: functions.HttpsFunction & functions.Runnable<any>;
export declare const getDeploymentStatus: functions.HttpsFunction & functions.Runnable<any>;
export declare const analyzeCheckup: functions.HttpsFunction & functions.Runnable<any>;
export declare const generate14DReport: functions.HttpsFunction & functions.Runnable<any>;
export declare const runSimulation: functions.HttpsFunction & functions.Runnable<any>;
export { submitChallengeResponse, submitBatchChallengeResponses, deleteChallengeResponse } from './firstOpinion/submitChallengeResponse';
export { syncMultipliers } from './firstOpinion/multiplierSync';
export { recalculateCycleScores } from './firstOpinion/recalculateOnDemand';
export { batchRecalculateAllCycles } from './firstOpinion/batch';
export { onChallengeResponseWrite, onMultiplierWrite } from './firstOpinion/triggers';
export { generateFirstOpinionReport } from './firstOpinion/generateFirstOpinionReport';
export { detectEarlyWarnings } from './firstOpinion/detectEarlyWarnings';
export { calculateMetrics } from './14d/calculateMetrics';
export { runGapAnalysis, isBlindSpot } from './14d/gapAnalysis';
export { generateRecommendations } from './14d/recommendations';
export { onCycleCompletion } from './firstOpinion/onCycleCompletion';
export { generateDiagnosticReport } from './analysis/generateReport';
export { analyzeDimensions } from './analysis/dimensionAnalysis';
export { analyzeTrends } from './analysis/trendAnalysis';
